-- Migration 002: Fix groups.admin_id and group_members.player_id from uuid → text
-- The app uses player names (e.g. "Murray Sirel") not UUIDs for these columns.
-- Run in the Supabase SQL editor.

-- Drop FK constraints first (names are auto-generated by Postgres)
ALTER TABLE groups        DROP CONSTRAINT IF EXISTS groups_admin_id_fkey;
ALTER TABLE group_members DROP CONSTRAINT IF EXISTS group_members_player_id_fkey;

-- Change column types to text
ALTER TABLE groups        ALTER COLUMN admin_id   TYPE text USING admin_id::text;
ALTER TABLE group_members ALTER COLUMN player_id  TYPE text USING player_id::text;
